[versions]
androidGradlePlugin = "8.2.2"
androidxActivity = "1.9.2"
androidxAppcompat = "1.7.0"
androidxCore = "1.13.1"
material3 = "1.3.0"
kotlin = "1.9.22"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
material3 = { module = "com.google.android.material:material", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
