name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Assemble debug
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Decode release keystore
        if: ${{ github.ref == 'refs/heads/main' && secrets.SIGNING_STORE_BASE64 != '' }}
        run: |
          echo "${{ secrets.SIGNING_STORE_BASE64 }}" | base64 -d > keystore.jks
          echo "SIGNING_STORE_FILE=keystore.jks" >> $GITHUB_ENV

      - name: Assemble release
        if: ${{ github.ref == 'refs/heads/main' && secrets.SIGNING_STORE_BASE64 != '' }}
        env:
          SIGNING_STORE_FILE: ${{ env.SIGNING_STORE_FILE }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload release APK
        if: ${{ github.ref == 'refs/heads/main' && secrets.SIGNING_STORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
