name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v2

      - name: Restore Gradle cache
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Decode release keystore
        if: ${{ secrets.SIGNING_STORE_BASE64 != '' }}
        run: |
          echo "${{ secrets.SIGNING_STORE_BASE64 }}" | base64 -d > keystore.jks
          echo "SIGNING_STORE_FILE=keystore.jks" >> $GITHUB_ENV

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Build release APK
        env:
          SIGNING_STORE_FILE: ${{ env.SIGNING_STORE_FILE }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
